name: Release new version
on:
  push:
    tags:
      - v(.*)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    - name: Build
      run: |
        echo "-X main.version=$GITHUB_REF -X main.revision=$GITHUB_SHA -X main.date=$(date --iso-8601=seconds)" > /tmp/buildtags
        cat /tmp/buildtags

        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o tmpl -ldflags "-s -d -w $(cat /tmp/buildtags)" -mod=vendor .
